### ISSUE TITLE
fail on start

### ISSUE THREAD

**Issue by adocampo** [netaskd/ldap-ad-proxy#1]
Hello, 

I was trying your image, I've created like this
```
version: '3.3'
services:
    ldap-ad-proxy:
        container_name: ldap-ad
        ports:
            - '389:389'
        environment:
            - 'AD_SERVER_URI=ldap://192.168.10.10:389'
            - 'AD_BASEDN=OU=DC=domain,DC=int'
            - 'META_SUFFIX=OU=DC=domain,DC=int'
            - LOG_LEVEL=7
        image: 'netaskd/ldap-ad-proxy:latest'
```

And it gave this result when I try to start it
```
MQInRoutingServers $ frsComputerReference $ ipsecOwnersReference $ ipsecPolicyReference $ hasPartialReplicaNCs $ localPolicyReference $ ipsecFilterReference $ ipsecISAKMPReference $ fRSMemberReferenceBL $ nonSecurityMemberBL $ manager $ member $ owner $ roleOccupant $ documentAuthor $ secretary $ associatedName $ dITRedirect ) )
ldap-ad  | 646cf6b3     2.5.13.0 (objectIdentifierMatch): matchingRuleUse: ( 2.5.13.0 NAME 'objectIdentifierMatch' APPLIES ( supportedControl $ supportedExtension $ supportedFeatures $ allowedChildClasses $ systemMustContain $ possibleInferiors $ allowedAttributes $ systemMayContain $ attributeSyntax $ auxiliaryClass $ possSuperiors $ mustContain $ attributeID $ subClassOf $ mayContain $ governsID $ allowedChildClassesEffective $ rDNAttID $ allowedAttributesEffective $ transportAddressAttribute $ systemAuxiliaryClass $ systemPossSuperiors $ supportedApplicationContext ) )
ldap-ad  | config file testing succeeded
ldap-ad  | ldap_url_parse_ext(ldap://localhost/)
ldap-ad  | ldap_init: trying /etc/openldap/ldap.conf
ldap-ad  | ldap_init: using /etc/openldap/ldap.conf
ldap-ad  | ldap_init: HOME env is /root
ldap-ad  | ldap_init: trying /root/ldaprc
ldap-ad  | ldap_init: trying /root/.ldaprc
ldap-ad  | ldap_init: trying ldaprc
ldap-ad  | ldap_init: LDAPCONF env is NULL
ldap-ad  | ldap_init: LDAPRC env is NULL
ldap-ad  | 646cf6b3 @(#) $OpenLDAP: slapd 2.4.47 (Jul  5 2019 14:05:40) $
ldap-ad  |      @1dd3f8401193:/work/main/openldap/src/openldap-2.4.47/servers/slapd
ldap-ad  | ldap_pvt_gethostbyname_a: host=b07311956704, r=0
ldap-ad  | 646cf6b3 daemon_init: ldap:/// ldaps:///
ldap-ad  | 646cf6b3 ch_calloc of 1 elems of 60129541696 bytes failed
ldap-ad  | Assertion failed: 0 (ch_malloc.c: ch_calloc: 107)
ldap-ad  | Aborted (core dumped)
ldap-ad exited with code 134

```

Any ideas?
